apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishstore
  labels:
    app: fishstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishstore
  template:
    metadata:
      labels:
        app: fishstore
    spec:
      containers:
        - name: fishstore
          image: username/fishstore:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5